name       : python-gitpython
version    : 2.1.7
release    : 1
source     :
    - https://github.com/gitpython-developers/GitPython/archive/2.1.7.tar.gz : 6966c4d91c9e8c0d782446157c123d009297fb36addcf6b1f55e1ec258c26b11
license    : BSD-3-Clause
component  : programming.python
summary    : GitPython is a python library used to interact with git repositories, high-level like git-porcelain, or low-level like git-plumbing.
description: |
    GitPython is a python library used to interact with git repositories, high-level like git-porcelain, or low-level like git-plumbing.
builddeps  :
    - python-gitdb2
    - python-setuptools
rundeps    :
    - git
    - python-gitdb2    
build      : |
    %python_setup
install    : |
    %python_install
